[config]

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.hyprland]
input_path = './templates/colors.css'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/colors.css'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'


[templates.gtk3]
input_path = './templates/colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/colors.css'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.wlogout]
input_path = './templates/colors.css'
output_path = '~/.config/wlogout/colors.css'


[templates.rofi]
input_path = './templates/colors.css'
output_path = '~/.config/rofi/colors.rasi'


[templates.pywalfox]
input_path = './templates/colors.css'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[config]

[templates.btop]
input_path = './templates/colors.css'
output_path = '~/.config/btop/themes/matugen.theme'